PROCESSOR 16F887
#include <xc.inc>
;CONFIG 1
CONFIG FOSC = INTRC_NOCLKOUT
CONFIG WDTE = OFF
CONFIG PWRTE = ON
CONFIG MCLRE = OFF
CONFIG CP = OFF
CONFIG CPD = OFF
CONFIG BOREN = OFF
CONFIG IESO = OFF
CONFIG FCMEN = ON
CONFIG DEBUG = ON
;CONFIG 2
CONFIG BOR4V=BOR40V
CONFIG WRT = OFF
    PSECT udata
retraso1:
    DS 1
retraso2:
    DS 1
retraso3:
    DS 1
PSECT resetVec,class=CODE,delta=2
resetVec:
PAGESEL main
goto main
PSECT code
main:
BANKSEL ANSELH
CLRF ANSELH
BANKSEL TRISC
MOVLW 0b00000000
MOVWF TRISC
BANKSEL PORTC
CLRF PORTC
bcf STATUS,5
bsf STATUS,6
bcf STATUS,0
BANKSEL OSCCON
MOVLW  0b01110000
MOVWF  OSCCON
INICIO:
bcf STATUS,0
bcf STATUS,5
bcf STATUS,6
MOVLW   0b00000001
MOVWF   PORTC
GOTO INCREMENTOIZQUIERDA
INCREMENTOIZQUIERDA:
RLF PORTC
BTFSS PORTC,7
GOTO INCREMENTOIZQUIERDA
GOTO INCREMENTODERECHA 
INCREMENTODERECHA:
RRF PORTC
BTFSS PORTC,0
GOTO INCREMENTODERECHA
GOTO INICIO 
END